// src/lib/entities/project/ui/ProjectCard.tsx
import Link from 'next/link';
import { Box, styled } from 'styled-system/jsx';
import type { ProjectSummary } from '@/lib/entities/project';

const CardLink = styled(Link);

export default function ProjectCard({ project }: { project: ProjectSummary }) {
	return (
		<CardLink
			href={`/projects/${project.slug}`}
			className="group"
			display="block"
			bg="surface.muted"
			borderRadius="xl"
			overflow="hidden"
			transition="all {durations.slow}"
			transitionTimingFunction="cubic-bezier(0.4, 0, 0.2, 1)"
			_hover={{ bg: 'surface.subtle', transform: 'translateY(-8px)' }}
		>
			<Box w="100%" h="48" bg="border" overflow="hidden">
				<styled.img
					src={project.image}
					alt={project.title}
					w="100%"
					h="100%"
					objectFit="cover"
					transition="transform {durations.slow}"
					transitionTimingFunction="ease-out"
					_groupHover={{ transform: 'scale(1.05)' }}
				/>
			</Box>
			<Box p="5">
				<styled.h3 fontSize="lg" fontWeight="bold" mb="2" color="text">
					{project.title}
				</styled.h3>
				<styled.p color="text.muted" lineHeight="relaxed" fontSize="sm">
					{project.excerpt}
				</styled.p>
			</Box>
		</CardLink>
	);
}

// src/lib/entities/project/ui/ProjectCard.svelte
<script lang="ts">
	import { css, cx } from 'styled-system/css';
	import type { Project } from '$lib/entities/project';

	interface Props {
		project: Project;
	}

	let { project }: Props = $props();
</script>

<a
	href={`/projects/${project.slug}`}
	class={cx(
		'group',
		css({
			display: 'block',
			bg: 'surface.muted',
			borderRadius: 'xl',
			overflow: 'hidden',
			transition: 'all {durations.slow}',
			transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
			_hover: {
				bg: 'surface.subtle',
				transform: 'translateY(-8px)'
			}
		})
	)}
>
	<div
		class={css({
			w: '100%',
			h: '48',
			bg: 'border',
			overflow: 'hidden'
		})}
	>
		<img
			src={project.image}
			alt={project.title}
			class={css({
				w: '100%',
				h: '100%',
				objectFit: 'cover',
				transition: 'transform {durations.slow}',
				transitionTimingFunction: 'ease-out',
				_groupHover: {
					transform: 'scale(1.05)'
				}
			})}
		/>
	</div>
	<div class={css({ p: '5' })}>
		<h3
			class={css({
				fontSize: 'lg',
				fontWeight: 'bold',
				mb: '2',
				color: 'text'
			})}
		>
			{project.title}
		</h3>
		<p
			class={css({
				color: 'text.muted',
				lineHeight: 'relaxed',
				fontSize: 'sm'
			})}
		>
			{project.excerpt}
		</p>
	</div>
</a>
